name: HerokuDeploy

on:
  push:
    branches:
      - starfire

jobs:
  frostdeploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/starfire'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.FROST_HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.FROST_APP_NAME}}
          heroku_email: ${{secrets.FROST_EMAIL}}
